// Date: 5/23/2015 9:26:05 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Items.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFreddysMic extends ModelBase
{
  //fields
    ModelRenderer michandle;
    ModelRenderer mic;
  
  public ModelFreddysMic()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      michandle = new ModelRenderer(this, 40, 16);
      michandle.addBox(-3F, -2F, -2F, 1, 4, 1);
      michandle.setRotationPoint(2F, 22F, 0F);
      michandle.setTextureSize(64, 32);
      michandle.mirror = true;
      setRotation(michandle, 0F, 0F, 0F);
      mic = new ModelRenderer(this, 40, 6);
      mic.addBox(-1F, -2F, -2F, 3, 3, 3);
      mic.setRotationPoint(-1F, 19F, -1F);
      mic.setTextureSize(64, 32);
      mic.mirror = true;
      setRotation(mic, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    michandle.render(f5);
    mic.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
