// Date: 5/23/2015 9:23:20 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Blocks.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelChicaPlushie extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
    ModelRenderer hairstrand1;
    ModelRenderer hairstrand2;
  
  public ModelChicaPlushie()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 30, 1);
      head.addBox(-4F, -8F, -4F, 3, 3, 3);
      head.setRotationPoint(2F, 24F, 3F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 31, 9);
      body.addBox(-4F, 0F, -2F, 3, 4, 2);
      body.setRotationPoint(2F, 19F, 2F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 44, 11);
      rightarm.addBox(-3F, -2F, -2F, 1, 3, 1);
      rightarm.setRotationPoint(-2F, 22F, 2F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.7853982F);
      leftarm = new ModelRenderer(this, 25, 10);
      leftarm.addBox(-1F, -2F, -2F, 1, 3, 1);
      leftarm.setRotationPoint(3F, 20F, 2F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.6632251F);
      leftleg = new ModelRenderer(this, 26, 16);
      leftleg.addBox(-2F, 0F, -2F, 1, 1, 4);
      leftleg.setRotationPoint(2F, 23F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, -0.0872665F, 0F);
      rightleg = new ModelRenderer(this, 38, 16);
      rightleg.addBox(0F, 0F, 0F, 1, 1, 4);
      rightleg.setRotationPoint(-2F, 23F, -2F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0.0872665F, 0F);
      hairstrand1 = new ModelRenderer(this, 53, 16);
      hairstrand1.addBox(0F, 0F, 0F, 1, 2, 1);
      hairstrand1.setRotationPoint(-1F, 14F, 0F);
      hairstrand1.setTextureSize(64, 32);
      hairstrand1.mirror = true;
      setRotation(hairstrand1, 0F, 0F, 0F);
      hairstrand2 = new ModelRenderer(this, 59, 16);
      hairstrand2.addBox(0F, 0F, 0F, 1, 1, 1);
      hairstrand2.setRotationPoint(-2F, 15F, 1F);
      hairstrand2.setTextureSize(64, 32);
      hairstrand2.mirror = true;
      setRotation(hairstrand2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    leftleg.render(f5);
    rightleg.render(f5);
    hairstrand1.render(f5);
    hairstrand2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
