// Date: 5/9/2015 6:58:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Blocks.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLootBoxOpen extends ModelBase
{
  //fields
    ModelRenderer Box;
    ModelRenderer Top;
  
  public ModelLootBoxOpen()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Box = new ModelRenderer(this, 0, 0);
      Box.addBox(0F, 0F, 0F, 4, 2, 4);
      Box.setRotationPoint(-2F, 22F, -2F);
      Box.setTextureSize(32, 32);
      Box.mirror = true;
      setRotation(Box, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(0F, 0F, 0F, 4, 1, 4);
      Top.setRotationPoint(-2F, 22F, -2F);
      Top.setTextureSize(32, 32);
      Top.mirror = true;
      setRotation(Top, 0F, 0.0174533F, -1.082104F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Box.render(f5);
    Top.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
