// Date: 5/23/2015 9:22:38 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Blocks.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBBPlushie extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer hatthingy;
    ModelRenderer balloon1;
    ModelRenderer balloon2;
  
  public ModelBBPlushie()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 33, 1);
      head.addBox(-4F, -8F, -4F, 3, 3, 3);
      head.setRotationPoint(2F, 23F, 1F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 34, 8);
      body.addBox(-4F, 0F, -2F, 3, 4, 2);
      body.setRotationPoint(2F, 18F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 47, 9);
      rightarm.addBox(-3F, -2F, -2F, 3, 1, 1);
      rightarm.setRotationPoint(-2F, 20F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 27, 9);
      leftarm.addBox(-1F, -2F, -2F, 1, 3, 1);
      leftarm.setRotationPoint(2F, 20F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 45, 16);
      rightleg.addBox(-2F, 0F, -2F, 1, 2, 1);
      rightleg.setRotationPoint(0F, 22F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 29, 16);
      leftleg.addBox(-2F, 0F, -2F, 1, 2, 1);
      leftleg.setRotationPoint(2F, 22F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      hatthingy = new ModelRenderer(this, 47, 3);
      hatthingy.addBox(0F, 0F, 0F, 1, 1, 1);
      hatthingy.setRotationPoint(-1F, 14F, -2F);
      hatthingy.setTextureSize(64, 32);
      hatthingy.mirror = true;
      setRotation(hatthingy, 0F, 0F, 0F);
      balloon1 = new ModelRenderer(this, 6, 16);
      balloon1.addBox(0F, 0F, 0F, 1, 2, 1);
      balloon1.setRotationPoint(-5F, 16F, -2F);
      balloon1.setTextureSize(64, 32);
      balloon1.mirror = true;
      setRotation(balloon1, 0F, 0F, 0F);
      balloon2 = new ModelRenderer(this, 2, 5);
      balloon2.addBox(0F, 0F, 0F, 3, 3, 3);
      balloon2.setRotationPoint(-6F, 13F, -3F);
      balloon2.setTextureSize(64, 32);
      balloon2.mirror = true;
      setRotation(balloon2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    hatthingy.render(f5);
    balloon1.render(f5);
    balloon2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
