// Date: 6/19/2015 10:06:42 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Entity.fnati.NM;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class NegativeMickey extends ModelBase
{
  //fields
    ModelRenderer Right_Leg_1;
    ModelRenderer Left_Leg_1;
    ModelRenderer Right_Leg_2;
    ModelRenderer Left_Leg_2;
    ModelRenderer Right_Leg_3;
    ModelRenderer Left_Leg_3;
    ModelRenderer Right_Leg_4;
    ModelRenderer Left_Leg_4;
    ModelRenderer Body_1;
    ModelRenderer Body_2;
    ModelRenderer Neck;
    ModelRenderer Head_1;
    ModelRenderer Head_2;
    ModelRenderer Head_3;
    ModelRenderer Nose;
    ModelRenderer Right_Ear;
    ModelRenderer Left_Ear;
    ModelRenderer Right_Arm_1;
    ModelRenderer Right_Arm_2;
    ModelRenderer Right_Hand;
    ModelRenderer Right_Leg_5;
    ModelRenderer Left_Leg_5;
    ModelRenderer Left_Arm_1;
    ModelRenderer Left_Arm_2;
    ModelRenderer Left_Hand;
    ModelRenderer Right_Finger_1;
    ModelRenderer Right_Finger_2;
    ModelRenderer Right_Finger_3;
    ModelRenderer Right_Finger_4;
    ModelRenderer Left_Finger_1;
    ModelRenderer Left_Finger_2;
    ModelRenderer Left_Finger_3;
    ModelRenderer Left_Finger_4;
    ModelRenderer Tail_1;
    ModelRenderer Tail_2;
    ModelRenderer Tail_3;
  
  public NegativeMickey()
  {
    textureWidth = 128;
    textureHeight = 64;
    
   //   Right_Leg_1.mirror = true;
      Right_Leg_1 = new ModelRenderer(this, 0, 0);
      Right_Leg_1.addBox(-2F, 0F, -4F, 4, 2, 6);
      Right_Leg_1.setRotationPoint(-2F, 22F, 0F);
      Right_Leg_1.setTextureSize(128, 64);
      Right_Leg_1.mirror = true;
      setRotation(Right_Leg_1, 0F, 0.0523599F, 0F);
      Right_Leg_1.mirror = false;
      Left_Leg_1 = new ModelRenderer(this, 0, 0);
      Left_Leg_1.addBox(-2F, 0F, -4F, 4, 2, 6);
      Left_Leg_1.setRotationPoint(2F, 22F, 0F);
      Left_Leg_1.setTextureSize(128, 64);
      Left_Leg_1.mirror = true;
      setRotation(Left_Leg_1, 0F, -0.0523599F, 0F);
      Right_Leg_2 = new ModelRenderer(this, 0, 12);
      Right_Leg_2.addBox(-1F, 0F, -1F, 2, 3, 2);
      Right_Leg_2.setRotationPoint(-2F, 20F, 0F);
      Right_Leg_2.setTextureSize(128, 64);
      Right_Leg_2.mirror = true;
      setRotation(Right_Leg_2, 0F, 0F, 0F);
      Left_Leg_2 = new ModelRenderer(this, 0, 12);
      Left_Leg_2.addBox(-1F, 0F, -1F, 2, 3, 2);
      Left_Leg_2.setRotationPoint(2F, 20F, 0F);
      Left_Leg_2.setTextureSize(128, 64);
      Left_Leg_2.mirror = true;
      setRotation(Left_Leg_2, 0F, 0F, 0F);
      Right_Leg_3 = new ModelRenderer(this, 0, 12);
      Right_Leg_3.addBox(-1F, 0F, -1F, 2, 3, 2);
      Right_Leg_3.setRotationPoint(-2F, 17F, 0F);
      Right_Leg_3.setTextureSize(128, 64);
      Right_Leg_3.mirror = true;
      setRotation(Right_Leg_3, 0F, 0F, 0F);
      Left_Leg_3 = new ModelRenderer(this, 0, 12);
      Left_Leg_3.addBox(-1F, 0F, -1F, 2, 3, 2);
      Left_Leg_3.setRotationPoint(2F, 17F, 0F);
      Left_Leg_3.setTextureSize(128, 64);
      Left_Leg_3.mirror = true;
      setRotation(Left_Leg_3, 0F, 0F, 0F);
      Right_Leg_4 = new ModelRenderer(this, 0, 20);
      Right_Leg_4.addBox(-1.5F, 0F, -1.466667F, 2, 3, 3);
      Right_Leg_4.setRotationPoint(-1.6F, 15F, 0F);
      Right_Leg_4.setTextureSize(128, 64);
      Right_Leg_4.mirror = true;
      setRotation(Right_Leg_4, 0F, 0F, 0F);
      Left_Leg_4 = new ModelRenderer(this, 0, 20);
      Left_Leg_4.addBox(-0.4666667F, 0F, -1.466667F, 2, 3, 3);
      Left_Leg_4.setRotationPoint(1.6F, 15F, 0F);
      Left_Leg_4.setTextureSize(128, 64);
      Left_Leg_4.mirror = true;
      setRotation(Left_Leg_4, 0F, 0F, 0F);
      Body_1 = new ModelRenderer(this, 40, 52);
      Body_1.addBox(-3F, 0F, -2.5F, 6, 5, 5);
      Body_1.setRotationPoint(0F, 10F, 0F);
      Body_1.setTextureSize(128, 64);
      Body_1.mirror = true;
      setRotation(Body_1, 0F, 0F, 0F);
      Body_2 = new ModelRenderer(this, 66, 52);
      Body_2.addBox(-2.5F, 0F, -2.466667F, 5, 4, 5);
      Body_2.setRotationPoint(0F, 6F, 0F);
      Body_2.setTextureSize(128, 64);
      Body_2.mirror = true;
      setRotation(Body_2, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 30, 52);
      Neck.addBox(-1F, -2F, -1F, 2, 2, 2);
      Neck.setRotationPoint(0F, 6F, 0F);
      Neck.setTextureSize(128, 64);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      Head_1 = new ModelRenderer(this, 51, 32);
      Head_1.addBox(-2.5F, 1F, -3F, 5, 1, 3);
      Head_1.setRotationPoint(0F, 3.5F, 0F);
      Head_1.setTextureSize(128, 64);
      Head_1.mirror = true;
      setRotation(Head_1, 0F, 0F, 0F);
      Head_2 = new ModelRenderer(this, 50, 18);
      Head_2.addBox(-3.033333F, -5F, -3F, 6, 6, 6);
      Head_2.setRotationPoint(0F, 3.533333F, 0F);
      Head_2.setTextureSize(128, 64);
      Head_2.mirror = true;
      setRotation(Head_2, 0F, 0F, 0F);
      Head_3 = new ModelRenderer(this, 37, 32);
      Head_3.addBox(-1.5F, -1.5F, -4.666667F, 3, 2, 2);
      Head_3.setRotationPoint(0F, 3.533333F, 0F);
      Head_3.setTextureSize(128, 64);
      Head_3.mirror = true;
      setRotation(Head_3, 0F, 0F, 0F);
      Nose = new ModelRenderer(this, 28, 32);
      Nose.addBox(-1.033333F, -1.6F, -5.066667F, 2, 1, 1);
      Nose.setRotationPoint(0F, 3.533333F, 0F);
      Nose.setTextureSize(128, 64);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      Right_Ear = new ModelRenderer(this, 44, 8);
      Right_Ear.addBox(-6.033333F, -8F, 0F, 4, 4, 1);
      Right_Ear.setRotationPoint(0F, 3.533333F, 0F);
      Right_Ear.setTextureSize(128, 64);
      Right_Ear.mirror = true;
      setRotation(Right_Ear, 0F, 0F, 0F);
      Left_Ear = new ModelRenderer(this, 44, 8);
      Left_Ear.addBox(1.966667F, -8F, 0F, 4, 4, 1);
      Left_Ear.setRotationPoint(0F, 3.533333F, 0F);
      Left_Ear.setTextureSize(128, 64);
      Left_Ear.mirror = true;
      setRotation(Left_Ear, 0F, 0F, 0F);
      Right_Arm_1 = new ModelRenderer(this, 0, 32);
      Right_Arm_1.addBox(-1F, 0F, -1F, 2, 5, 2);
      Right_Arm_1.setRotationPoint(-3F, 6F, 0F);
      Right_Arm_1.setTextureSize(128, 64);
      Right_Arm_1.mirror = true;
      setRotation(Right_Arm_1, 0F, 0F, 0.3490659F);
      Right_Arm_2 = new ModelRenderer(this, 0, 42);
      Right_Arm_2.addBox(-1F, 0F, -1F, 2, 3, 2);
      Right_Arm_2.setRotationPoint(-4.5F, 10F, 0F);
      Right_Arm_2.setTextureSize(128, 64);
      Right_Arm_2.mirror = true;
      setRotation(Right_Arm_2, 0F, 0F, 0F);
      Right_Hand = new ModelRenderer(this, 11, 52);
      Right_Hand.addBox(-1F, 3F, -1.5F, 2, 3, 3);
      Right_Hand.setRotationPoint(-4.5F, 10F, 0F);
      Right_Hand.setTextureSize(128, 64);
      Right_Hand.mirror = true;
      setRotation(Right_Hand, 0F, 0F, 0F);
      Right_Leg_5 = new ModelRenderer(this, 0, 20);
      Right_Leg_5.addBox(0.03333334F, 0F, -1.466667F, 1, 3, 3);
      Right_Leg_5.setRotationPoint(-1.6F, 15F, 0F);
      Right_Leg_5.setTextureSize(128, 64);
      Right_Leg_5.mirror = true;
      setRotation(Right_Leg_5, 0F, 0F, 0F);
      Left_Leg_5 = new ModelRenderer(this, 0, 20);
      Left_Leg_5.addBox(-1F, 0F, -1.466667F, 1, 3, 3);
      Left_Leg_5.setRotationPoint(1.6F, 15F, 0F);
      Left_Leg_5.setTextureSize(128, 64);
      Left_Leg_5.mirror = true;
      setRotation(Left_Leg_5, 0F, 0F, 0F);
      Left_Arm_1 = new ModelRenderer(this, 0, 32);
      Left_Arm_1.addBox(-1F, 0F, -1F, 2, 5, 2);
      Left_Arm_1.setRotationPoint(3F, 6F, 0F);
      Left_Arm_1.setTextureSize(128, 64);
      Left_Arm_1.mirror = true;
      setRotation(Left_Arm_1, 0F, 0F, -0.3490659F);
      Left_Arm_2 = new ModelRenderer(this, 0, 42);
      Left_Arm_2.addBox(-1F, 0F, -1F, 2, 3, 2);
      Left_Arm_2.setRotationPoint(4.5F, 10F, 0F);
      Left_Arm_2.setTextureSize(128, 64);
      Left_Arm_2.mirror = true;
      setRotation(Left_Arm_2, 0F, 0F, 0F);
   //   Left_Hand.mirror = true;
      Left_Hand = new ModelRenderer(this, 11, 52);
      Left_Hand.addBox(-1F, 3F, -1.5F, 2, 3, 3);
      Left_Hand.setRotationPoint(4.5F, 10F, 0F);
      Left_Hand.setTextureSize(128, 64);
      Left_Hand.mirror = true;
      setRotation(Left_Hand, 0F, 0F, 0F);
      Left_Hand.mirror = false;
      Right_Finger_1 = new ModelRenderer(this, 0, 52);
      Right_Finger_1.addBox(-1F, 6F, -1.5F, 1, 2, 1);
      Right_Finger_1.setRotationPoint(-4.5F, 10F, 0F);
      Right_Finger_1.setTextureSize(128, 64);
      Right_Finger_1.mirror = true;
      setRotation(Right_Finger_1, 0F, 0F, 0F);
      Right_Finger_2 = new ModelRenderer(this, 0, 52);
      Right_Finger_2.addBox(-1F, 6F, 0.5F, 1, 2, 1);
      Right_Finger_2.setRotationPoint(-4.5F, 10F, 0F);
      Right_Finger_2.setTextureSize(128, 64);
      Right_Finger_2.mirror = true;
      setRotation(Right_Finger_2, 0F, 0F, 0F);
      Right_Finger_3 = new ModelRenderer(this, 0, 52);
      Right_Finger_3.addBox(-1.333333F, 6F, -0.5F, 1, 2, 1);
      Right_Finger_3.setRotationPoint(-4.5F, 10F, 0F);
      Right_Finger_3.setTextureSize(128, 64);
      Right_Finger_3.mirror = true;
      setRotation(Right_Finger_3, 0F, 0F, 0F);
      Right_Finger_4 = new ModelRenderer(this, 0, 52);
      Right_Finger_4.addBox(0F, 5.666667F, -1.9F, 1, 2, 1);
      Right_Finger_4.setRotationPoint(-4.5F, 10F, 0F);
      Right_Finger_4.setTextureSize(128, 64);
      Right_Finger_4.mirror = true;
      setRotation(Right_Finger_4, 0F, 0F, 0F);
      Left_Finger_1 = new ModelRenderer(this, 0, 52);
      Left_Finger_1.addBox(0F, 6F, -1.5F, 1, 2, 1);
      Left_Finger_1.setRotationPoint(4.5F, 10F, 0F);
      Left_Finger_1.setTextureSize(128, 64);
      Left_Finger_1.mirror = true;
      setRotation(Left_Finger_1, 0F, 0F, 0F);
      Left_Finger_2 = new ModelRenderer(this, 0, 52);
      Left_Finger_2.addBox(0F, 6F, 0.5F, 1, 2, 1);
      Left_Finger_2.setRotationPoint(4.5F, 10F, 0F);
      Left_Finger_2.setTextureSize(128, 64);
      Left_Finger_2.mirror = true;
      setRotation(Left_Finger_2, 0F, 0F, 0F);
      Left_Finger_3 = new ModelRenderer(this, 0, 52);
      Left_Finger_3.addBox(0.3F, 6F, -0.5F, 1, 2, 1);
      Left_Finger_3.setRotationPoint(4.5F, 10F, 0F);
      Left_Finger_3.setTextureSize(128, 64);
      Left_Finger_3.mirror = true;
      setRotation(Left_Finger_3, 0F, 0F, 0F);
      Left_Finger_4 = new ModelRenderer(this, 0, 52);
      Left_Finger_4.addBox(-1F, 5.666667F, -1.9F, 1, 2, 1);
      Left_Finger_4.setRotationPoint(4.5F, 10F, 0F);
      Left_Finger_4.setTextureSize(128, 64);
      Left_Finger_4.mirror = true;
      setRotation(Left_Finger_4, 0F, 0F, 0F);
      Tail_1 = new ModelRenderer(this, 71, 52);
      Tail_1.addBox(-0.5333334F, 0F, -0.5F, 1, 1, 5);
      Tail_1.setRotationPoint(0F, 13F, 2F);
      Tail_1.setTextureSize(128, 64);
      Tail_1.mirror = true;
      setRotation(Tail_1, -0.6806784F, 0F, 0F);
      Tail_2 = new ModelRenderer(this, 71, 52);
      Tail_2.addBox(-0.5333334F, 0F, -0.5F, 1, 1, 5);
      Tail_2.setRotationPoint(0F, 15.53333F, 5.466667F);
      Tail_2.setTextureSize(128, 64);
      Tail_2.mirror = true;
      setRotation(Tail_2, -0.1919862F, 0F, 0F);
      Tail_3 = new ModelRenderer(this, 71, 52);
      Tail_3.addBox(-0.5333334F, 0F, -0.5F, 1, 1, 5);
      Tail_3.setRotationPoint(0F, 16.2F, 9.866667F);
      Tail_3.setTextureSize(128, 64);
      Tail_3.mirror = true;
      setRotation(Tail_3, 0.1745329F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Right_Leg_1.render(f5);
    Left_Leg_1.render(f5);
    Right_Leg_2.render(f5);
    Left_Leg_2.render(f5);
    Right_Leg_3.render(f5);
    Left_Leg_3.render(f5);
    Right_Leg_4.render(f5);
    Left_Leg_4.render(f5);
    Body_1.render(f5);
    Body_2.render(f5);
    Neck.render(f5);
    Head_1.render(f5);
    Head_2.render(f5);
    Head_3.render(f5);
    Nose.render(f5);
    Right_Ear.render(f5);
    Left_Ear.render(f5);
    Right_Arm_1.render(f5);
    Right_Arm_2.render(f5);
    Right_Hand.render(f5);
    Right_Leg_5.render(f5);
    Left_Leg_5.render(f5);
    Left_Arm_1.render(f5);
    Left_Arm_2.render(f5);
    Left_Hand.render(f5);
    Right_Finger_1.render(f5);
    Right_Finger_2.render(f5);
    Right_Finger_3.render(f5);
    Right_Finger_4.render(f5);
    Left_Finger_1.render(f5);
    Left_Finger_2.render(f5);
    Left_Finger_3.render(f5);
    Left_Finger_4.render(f5);
    Tail_1.render(f5);
    Tail_2.render(f5);
    Tail_3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
