// Date: 6/19/2015 12:43:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Entity.Phantom.bb;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class PhantomBalloonBoy extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape31;
    ModelRenderer Shape32;
    ModelRenderer Shape33;
    ModelRenderer Shape36;
    ModelRenderer Shape37;
    ModelRenderer Shape38;
    ModelRenderer Shape41;
    ModelRenderer Shape42;
  
  public PhantomBalloonBoy()
  {
    textureWidth = 128;
    textureHeight = 64;
    
     // Shape1.mirror = true;
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-2F, 0F, -5F, 4, 2, 7);
      Shape1.setRotationPoint(-3F, 22F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0.3839724F, 0F);
      Shape1.mirror = false;
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(-2F, 0F, -5F, 4, 2, 7);
      Shape2.setRotationPoint(3F, 22F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, -0.3839724F, 0F);
      Shape3 = new ModelRenderer(this, 0, 57);
      Shape3.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
      Shape3.setRotationPoint(-3F, 19F, 0F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0.3839724F, 0F);
      Shape4 = new ModelRenderer(this, 0, 57);
      Shape4.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
      Shape4.setRotationPoint(3F, 19F, 0F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, -0.3839724F, 0F);
      Shape5 = new ModelRenderer(this, 0, 57);
      Shape5.addBox(-1.5F, -1F, -1.5F, 3, 4, 3);
      Shape5.setRotationPoint(-3F, 15.46667F, 0F);
      Shape5.setTextureSize(128, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0.3839724F, 0F);
      Shape6 = new ModelRenderer(this, 0, 57);
      Shape6.addBox(-1.5F, -1F, -1.5F, 3, 4, 3);
      Shape6.setRotationPoint(3F, 15.46667F, 0F);
      Shape6.setTextureSize(128, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, -0.3839724F, 0F);
      Shape7 = new ModelRenderer(this, 0, 52);
      Shape7.addBox(-1F, 0F, -1F, 2, 2, 2);
      Shape7.setRotationPoint(-3F, 18F, 0F);
      Shape7.setTextureSize(128, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0.3839724F, 0F);
      Shape8 = new ModelRenderer(this, 0, 52);
      Shape8.addBox(-1F, 0F, -1F, 2, 2, 2);
      Shape8.setRotationPoint(3F, 18F, 0F);
      Shape8.setTextureSize(128, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, -0.3839724F, 0F);
      Shape9 = new ModelRenderer(this, 15, 47);
      Shape9.addBox(-4F, -1F, -4F, 8, 8, 8);
      Shape9.setRotationPoint(0F, 8.5F, 0F);
      Shape9.setTextureSize(128, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 16, 24);
      Shape10.addBox(-3.5F, 0F, -3.5F, 7, 1, 7);
      Shape10.setRotationPoint(0F, 6.466667F, 0F);
      Shape10.setTextureSize(128, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 15, 33);
      Shape11.addBox(-5F, -0.4666667F, -3.5F, 1, 7, 7);
      Shape11.setRotationPoint(0F, 8.466666F, 0F);
      Shape11.setTextureSize(128, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 15, 33);
      Shape12.addBox(4F, -0.4666667F, -3.5F, 1, 7, 7);
      Shape12.setRotationPoint(0F, 8.466666F, 0F);
      Shape12.setTextureSize(128, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 32, 39);
      Shape13.addBox(-3.5F, -0.5F, -5F, 7, 7, 1);
      Shape13.setRotationPoint(0F, 8.466666F, 0F);
      Shape13.setTextureSize(128, 64);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 32, 39);
      Shape14.addBox(-3.5F, -0.5F, 4F, 7, 7, 1);
      Shape14.setRotationPoint(0F, 8.466666F, 0F);
      Shape14.setTextureSize(128, 64);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 35, 20);
      Shape15.addBox(-1F, -1F, -1F, 2, 1, 2);
      Shape15.setRotationPoint(0F, 6.466667F, 0F);
      Shape15.setTextureSize(128, 64);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 47, 14);
      Shape16.addBox(-3F, 0F, -3.5F, 6, 1, 7);
      Shape16.setRotationPoint(0F, 5F, 0F);
      Shape16.setTextureSize(128, 64);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 47, 1);
      Shape17.addBox(-3.5F, 2F, -3.5F, 7, 5, 7);
      Shape17.setRotationPoint(0F, -2F, 0F);
      Shape17.setTextureSize(128, 64);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 78, 0);
      Shape18.addBox(-4F, 0F, -4F, 8, 2, 8);
      Shape18.setRotationPoint(0F, -2F, 0F);
      Shape18.setTextureSize(128, 64);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 78, 12);
      Shape19.addBox(-3.5F, -1F, -3.5F, 7, 1, 7);
      Shape19.setRotationPoint(0F, -2F, 0F);
      Shape19.setTextureSize(128, 64);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 33, 0);
      Shape20.addBox(-1.5F, -2F, -1.5F, 3, 1, 3);
      Shape20.setRotationPoint(0F, -1.5F, 0F);
      Shape20.setTextureSize(128, 64);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 73, 0);
      Shape21.addBox(-0.5F, -5F, -0.5F, 1, 4, 1);
      Shape21.setRotationPoint(0F, -2F, 0F);
      Shape21.setTextureSize(128, 64);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 105, 1);
      Shape22.addBox(-3.5F, -2F, -3.5F, 7, 0, 7);
      Shape22.setRotationPoint(0F, -4F, 0F);
      Shape22.setTextureSize(128, 64);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 0, 27);
      Shape23.addBox(-3F, -1.466667F, -1.5F, 3, 3, 3);
      Shape23.setRotationPoint(-4F, 9.466666F, 0F);
      Shape23.setTextureSize(128, 64);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, -0.7853982F);
      Shape24 = new ModelRenderer(this, 0, 21);
      Shape24.addBox(-6F, -1F, -1F, 4, 2, 2);
      Shape24.setRotationPoint(-4F, 9.466666F, 0F);
      Shape24.setTextureSize(128, 64);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, -0.9424778F);
      Shape25 = new ModelRenderer(this, 0, 39);
      Shape25.addBox(-9F, -1.5F, -1.5F, 3, 3, 3);
      Shape25.setRotationPoint(-4F, 9.466666F, 0F);
      Shape25.setTextureSize(128, 64);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, -0.9424778F);
      Shape31 = new ModelRenderer(this, 0, 27);
      Shape31.addBox(0F, -1.466667F, -1.5F, 3, 3, 3);
      Shape31.setRotationPoint(4F, 9.466666F, 0F);
      Shape31.setTextureSize(128, 64);
      Shape31.mirror = true;
      setRotation(Shape31, 0F, 0F, 0.7853982F);
      Shape32 = new ModelRenderer(this, 0, 21);
      Shape32.addBox(2F, -1F, -1F, 4, 2, 2);
      Shape32.setRotationPoint(4F, 9.466666F, 0F);
      Shape32.setTextureSize(128, 64);
      Shape32.mirror = true;
      setRotation(Shape32, 0F, 0F, 0.9424778F);
      Shape33 = new ModelRenderer(this, 0, 39);
      Shape33.addBox(6F, -1.5F, -1.5F, 3, 3, 3);
      Shape33.setRotationPoint(4F, 9.466666F, 0F);
      Shape33.setTextureSize(128, 64);
      Shape33.mirror = true;
      setRotation(Shape33, 0F, 0F, 0.9424778F);
   //   Shape36.mirror = true;
      Shape36 = new ModelRenderer(this, 48, 5);
      Shape36.addBox(0.6666667F, 0F, -1F, 2, 2, 1);
      Shape36.setRotationPoint(0F, 0.4666667F, -2.6F);
      Shape36.setTextureSize(128, 64);
      Shape36.mirror = true;
      setRotation(Shape36, 0F, 0F, 0F);
      Shape36.mirror = false;
      Shape37 = new ModelRenderer(this, 48, 5);
      Shape37.addBox(-2.7F, 0F, -1F, 2, 2, 1);
      Shape37.setRotationPoint(0F, 0.4666667F, -2.6F);
      Shape37.setTextureSize(128, 64);
      Shape37.mirror = true;
      setRotation(Shape37, 0F, 0F, 0F);
      Shape38 = new ModelRenderer(this, 47, 0);
      Shape38.addBox(-0.5F, 0F, -1F, 1, 2, 2);
      Shape38.setRotationPoint(0F, 2F, -2.4F);
      Shape38.setTextureSize(128, 64);
      Shape38.mirror = true;
      setRotation(Shape38, -0.5061455F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 39, 52);
      Shape41.addBox(-0.9666666F, -0.2333333F, -5.2F, 2, 2, 1);
      Shape41.setRotationPoint(0F, 8.466666F, 0F);
      Shape41.setTextureSize(128, 64);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape42 = new ModelRenderer(this, 39, 52);
      Shape42.addBox(-0.9666666F, 2.166667F, -5.2F, 2, 2, 1);
      Shape42.setRotationPoint(0F, 8.466666F, 0F);
      Shape42.setTextureSize(128, 64);
      Shape42.mirror = true;
      setRotation(Shape42, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape18.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape31.render(f5);
    Shape32.render(f5);
    Shape33.render(f5);
    Shape36.render(f5);
    Shape37.render(f5);
    Shape38.render(f5);
    Shape41.render(f5);
    Shape42.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
