// Date: 5/23/2015 9:24:23 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Blocks.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDesk extends ModelBase
{
  //fields
    ModelRenderer top;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer paperball1;
    ModelRenderer paperball2;
    ModelRenderer paperball3;
    ModelRenderer fan1;
    ModelRenderer fan2;
    ModelRenderer fan3;
    ModelRenderer cup;
    ModelRenderer straw1;
    ModelRenderer straw2;
  
  public ModelDesk()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      top = new ModelRenderer(this, 5, 0);
      top.addBox(-4F, -8F, -4F, 45, 3, 13);
      top.setRotationPoint(-19F, 21F, -1F);
      top.setTextureSize(128, 32);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 13, 18);
      leg1.addBox(0F, 0F, 0F, 2, 8, 2);
      leg1.setRotationPoint(20F, 16F, -5F);
      leg1.setTextureSize(128, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 13, 18);
      leg2.addBox(0F, 0F, 0F, 2, 8, 2);
      leg2.setRotationPoint(20F, 16F, 6F);
      leg2.setTextureSize(128, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 13, 18);
      leg3.addBox(0F, 0F, 0F, 2, 8, 2);
      leg3.setRotationPoint(-23F, 16F, -5F);
      leg3.setTextureSize(128, 32);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 13, 18);
      leg4.addBox(0F, 0F, 0F, 2, 8, 2);
      leg4.setRotationPoint(-23F, 16F, 6F);
      leg4.setTextureSize(128, 32);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      paperball1 = new ModelRenderer(this, 109, 6);
      paperball1.addBox(0F, 0F, 0F, 2, 2, 2);
      paperball1.setRotationPoint(-9F, 11F, 3F);
      paperball1.setTextureSize(128, 32);
      paperball1.mirror = true;
      setRotation(paperball1, 0F, 0F, 0F);
      paperball2 = new ModelRenderer(this, 117, 2);
      paperball2.addBox(0F, 0F, 0F, 2, 2, 2);
      paperball2.setRotationPoint(-13F, 11F, 5F);
      paperball2.setTextureSize(128, 32);
      paperball2.mirror = true;
      setRotation(paperball2, 0F, 0F, 0F);
      paperball3 = new ModelRenderer(this, 119, 8);
      paperball3.addBox(0F, 0F, 0F, 2, 2, 2);
      paperball3.setRotationPoint(7F, 11F, -3F);
      paperball3.setTextureSize(128, 32);
      paperball3.mirror = true;
      setRotation(paperball3, 0F, 0F, 0F);
      fan1 = new ModelRenderer(this, 101, 21);
      fan1.addBox(0F, 0F, 0F, 5, 1, 3);
      fan1.setRotationPoint(7F, 12F, 3F);
      fan1.setTextureSize(128, 32);
      fan1.mirror = true;
      setRotation(fan1, 0F, 0F, 0F);
      fan2 = new ModelRenderer(this, 70, 20);
      fan2.addBox(0F, 0F, 0F, 1, 2, 1);
      fan2.setRotationPoint(9F, 10F, 4F);
      fan2.setTextureSize(128, 32);
      fan2.mirror = true;
      setRotation(fan2, 0F, 0F, 0F);
      fan3 = new ModelRenderer(this, 78, 19);
      fan3.addBox(0F, 0F, 0F, 6, 6, 3);
      fan3.setRotationPoint(6.5F, 4F, 3F);
      fan3.setTextureSize(128, 32);
      fan3.mirror = true;
      setRotation(fan3, 0F, 0F, 0F);
      cup = new ModelRenderer(this, 0, 4);
      cup.addBox(0F, 0F, 0F, 3, 5, 3);
      cup.setRotationPoint(16F, 8F, 0F);
      cup.setTextureSize(128, 32);
      cup.mirror = true;
      setRotation(cup, 0F, 0F, 0F);
      straw1 = new ModelRenderer(this, 14, 9);
      straw1.addBox(0F, 0F, 0F, 1, 1, 1);
      straw1.setRotationPoint(17F, 7F, 1F);
      straw1.setTextureSize(128, 32);
      straw1.mirror = true;
      setRotation(straw1, 0F, 0F, 0F);
      straw2 = new ModelRenderer(this, 10, 2);
      straw2.addBox(0F, 0F, 0F, 3, 1, 1);
      straw2.setRotationPoint(16.9F, 6.1F, 1F);
      straw2.setTextureSize(128, 32);
      straw2.mirror = true;
      setRotation(straw2, 0F, 0F, -0.0698132F);
      fan1 = new ModelRenderer(this, 44, 24);
      fan1.addBox(0F, 0F, 0F, 5, 1, 3);
      fan1.setRotationPoint(5F, 12F, 0F);
      fan1.setTextureSize(128, 32);
      fan1.mirror = true;
      setRotation(fan1, 0F, 0.1919862F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    top.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    paperball1.render(f5);
    paperball2.render(f5);
    paperball3.render(f5);
    fan1.render(f5);
    fan2.render(f5);
    fan3.render(f5);
    cup.render(f5);
    straw1.render(f5);
    straw2.render(f5);
    fan1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
