// Date: 5/23/2015 9:22:47 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.fnaf.Common.Blocks.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBonniePlushie extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer leftear;
    ModelRenderer rightear;
    ModelRenderer leftarm;
  
  public ModelBonniePlushie()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 31, 3);
      head.addBox(-4F, -8F, -4F, 3, 3, 3);
      head.setRotationPoint(2F, 24F, 3F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 32, 11);
      body.addBox(-4F, 0F, -2F, 3, 4, 2);
      body.setRotationPoint(2F, 19F, 2F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 43, 12);
      rightarm.addBox(-3F, -2F, -2F, 1, 3, 1);
      rightarm.setRotationPoint(-1F, 22F, 2F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.5585054F);
      rightleg = new ModelRenderer(this, 39, 18);
      rightleg.addBox(-2F, 0F, -2F, 1, 1, 4);
      rightleg.setRotationPoint(0F, 23F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0.0872665F, 0F);
      leftleg = new ModelRenderer(this, 26, 18);
      leftleg.addBox(-2F, 0F, -2F, 1, 1, 4);
      leftleg.setRotationPoint(2F, 23F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, -0.0872665F, 0F);
      leftear = new ModelRenderer(this, 25, 4);
      leftear.addBox(0F, 0F, 0F, 1, 3, 1);
      leftear.setRotationPoint(0F, 13F, 0F);
      leftear.setTextureSize(64, 32);
      leftear.mirror = true;
      setRotation(leftear, 0F, 0F, 0F);
      rightear = new ModelRenderer(this, 45, 4);
      rightear.addBox(0F, 0F, 0F, 1, 3, 1);
      rightear.setRotationPoint(-2F, 13F, 0F);
      rightear.setTextureSize(64, 32);
      rightear.mirror = true;
      setRotation(rightear, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 26, 12);
      leftarm.addBox(0F, 0F, 0F, 1, 3, 1);
      leftarm.setRotationPoint(1F, 19F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.3839724F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    leftear.render(f5);
    rightear.render(f5);
    leftarm.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
